### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by BattleBornPMC** [The-Zandrax/NoMoreCooked#32]
[12:13:46 WARN]: [NoMoreCooked] Task #3374 for NoMoreCooked v0.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index must be between 0 and 40
        at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:75) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at NoMoreCooked-0.2.jar/nmc.core.ExpirationAutoChecker.run(ExpirationAutoChecker.java:56) ~[NoMoreCooked-0.2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Need help fixing this error!

**Comment by The-Zandrax** [comment]
Hello. 

I need you to fill in this Github support request correctly. 

Follow this : 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Minecraft Version:**
- E.g. 1.20.4

**Server Version:**
 - E.g. Paper 1.x

**Plugin Version**
- E.g. NoMoreCooked-0.0.5-RELEASE

**Comment by BattleBornPMC** [comment]
Sorry ill do it right!

**Describe the bug**
The issue does not show any issues in game luckily. Yet does constantly show in console so now and then. We removed the plugin a while back because it seemed unstable due to those issues. Now we're trying again and we got the same issue.

**To Reproduce**
I got no clue as it just seems to happen out of the blue sometimes. Though we do want items to take very long to spoil. Not sure if there is a cap on numbers?

**Expected behavior**
I expected no errors or warnings.

**Minecraft Version:**
1.21.1

**Server Version:**
paper-1.21.1.jar

**Plugin Version**
NoMoreCooked-0.2.jar

**Error  Code:**
```
[12:13:46 WARN]: [NoMoreCooked] Task #3374 for NoMoreCooked v0.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index must be between 0 and 40
at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:75) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at NoMoreCooked-0.2.jar/nmc.core.ExpirationAutoChecker.run(ExpirationAutoChecker.java:56) ~[NoMoreCooked-0.2.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by The-Zandrax** [comment]
Thanks for the details, at first glance it's a slot outside the player's inventory, do you have a plugin or something that adds slots to the player's inventory outside the classic inventory, armor and the left hand?

**Comment by BattleBornPMC** [comment]
Not that i know off, we do use a balance thing on the UI but i guess that would not be it?

**Comment by The-Zandrax** [comment]
May i get your plugin list ?

**Comment by BattleBornPMC** [comment]
Sure here you go
```
advancedregionmarket-3.5.3.jar
AxGraves-1.15.1.jar
AxKills-1.0.5.jar
BetonQuest.jar
blockprot-spigot-1.2.2-all.jar
ccShop-1.3.4.jar
CharacterCards-2.2.5.jar
ChestSort-14.1.2.jar
Citizens-2.0.35-b3568.jar
CombatLogX-11.5.0.0.1242.zip
craftbook-bukkit-5.0.0-SNAPSHOT-dist.jar
CustomCrops-3.6.17.jar
DesirePaths.jar
dtlTradersPlus-6.4.29.jar
EnchantmentDisabler-0.2.3.jar
EssentialsX-2.21.0-dev+117-c80bef9.jar
EssentialsXChat-2.21.0-dev+117-c80bef9.jar
EventWar-0.0.67.jar
FarmControl-1.3.0.jar
farmingupgrade-1.7.1.jar
fastasyncvoxelsniper-3.2.1.jar
FastAsyncWorldEdit-Paper-2.12.1-SNAPSHOT-968.jar
GPet-1.5.4.jar
GSit-1.10.0.jar
InteractiveBooks.jar
inventorystacks-2.1.2-BETA.jar
InvisibleItemFrames-2.16.1.jar
LockettePro-2.11.1.jar
LuckPerms-Bukkit-5.4.141.jar
maptowny-3.0.0-ALPHA-3.jar
MarriageMaster.jar
medieval-brewery-1.7.2-SNAPSHOT.jar
MobLimit.jar
ModelEngine-4.0.7.jar
multiverse-core-4.3.13.jar
MythicCrucible-2.1.0.jar
MythicMobs-5.7.2.jar
NDailyRewards-3.1.0.jar
NoCrafting-1.0-RELEASE.jar
NoMoreCooked-0.2.jar
nuvotifier.jar
oraxen-1.184.0.jar
PL-Hide-1.5.22.jar
PlaceholderAPI-2.11.6.jar
PlantNerfer.jar
ProtocolLib.jar
Rankup-3.14.4.jar
RealisticSeasons-11.4.0.jar
RoseLoot-1.2.19.jar
RPGHorses.jar
SiegeWar-2.14.1.jar
SimpleLockpicking-3.4.jar
sleep-most-5.5.1.jar
squaremap-paper-mc1.21.1-1.3.2.jar
StaffModeX.jar
TAB v4.1.8.jar
TheGoldEconomy-1.6.8.jar
ThirstBar-2.4a.jar
Towny-0.100.4.0.jar
TownyChat-0.116.jar
TownyChat-0.117.jar
TownyCultures-2.0.3.jar
TownyMenu-1.8.9.jar
TownyProvinces-2.2.0.jar
TownyResources-0.11.1.jar
Ultimate_BlockRegeneration-2.0.21.jar
UltimateTimber-3.2.0.jar
Vault.jar
Versus-1.5.1.jar
VotingPlugin.jar
Vulcan-2.9.1.jar
WelcomeBack-1.8.jar
worldguard-bukkit-7.0.12-dist.jar
WorldGuardExtraFlags.jar
```

**Comment by The-Zandrax** [comment]
Hello, here's a specific version that will no longer display the error in your console. 

If you don't mind, in order to help me understand the exact origin of the problem, add the `debug: true` line in the configuration and please provide me with the error that will be displayed, a message that will include all the information needed to identify the problematic item and slot. 

**Download Link :** [NoMoreCooked-2.1.jar](https://dl.complexify.fr/NoMoreCooked/Github/NoMoreCooked-0.2.1.jar)

_You can disable the option after the error has occured._

**Comment by BattleBornPMC** [comment]
Thanks! For some reason there is no debug option in my config? Do i need to remove the old one or should it override on restart.

Btw: Is it possible to disable spoiling for specific items like rotten flesh and spider eyes? Do i just put the timer to 0 or something?

**Comment by The-Zandrax** [comment]
Yes, you have to add it yourself, at the very bottom for example. Like this : `debug: true`

To disable expiration for a particular item, set the value to `-1`

**Comment by BattleBornPMC** [comment]
```
[18:33:10 WARN]: [NoMoreCooked] The item ItemStack{POTATO x 64, UNSPECIFIC_META:{meta-type=UNSPECIFIC, lore=[{"text":"","extra":[" "]}, {"text":"","extra":[{"text":"Will rot on 120026 minutes","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}], PublicBukkitValues={
    "nomorecooked:cookedtimestamp": 1732125600L,
    "nomorecooked:expiration": 120060
}}} in the slot -1 could not be modified in inventory of CraftPlayer{name=Aqita} (Aqita)
[18:33:10 WARN]: [NoMoreCooked] The item has lore of : [ , §7Will rot on 120026 minutes]
[18:33:10 WARN]: [NoMoreCooked] The item has display name of : 
[18:33:10 WARN]: [NoMoreCooked] The item is affected by NMC ? : true
```

**Comment by The-Zandrax** [comment]
Thanks for the details, I see that the potato stack is located in Aqita's -1 slot inventory, this is indeed not a valid slot, can you ask this person to provide a screen of his inventory with the location where this potato stack would be located?

**Comment by BattleBornPMC** [comment]
Weirdly i havent seen any more of these errors. I think it was based around a backpack item i totally forgot about that.

**Comment by The-Zandrax** [comment]
Okay, do you need any special support for this request ?
