### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by ToMrZen** [The-Zandrax/NoMoreCooked#7]
**Describe the bug**
As soon as I added your plugin to the server, after any crafting of the item, I get an error, and the plugin itself does not work. Maybe I missed something and I'm not doing it right?
java.lang.NoClassDefFoundError: dev/lone/itemsadder/api/CustomStack
 at nmc.listener.CraftingListener.isItemsAdderFood(CraftingListener.java:201) ~[NoMoreCooked-0.0.8c-RELEASE.jar:?]
 at nmc.listener.CraftingListener.onCraftEvent(CraftingListener.java:51) ~[NoMoreCooked-0.0.8c-RELEASE.jar:?]
 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor207.execute(Unknown Source) ~[?:?]
 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3237) ~[?:?]
 at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
 at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
 at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
 at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
 at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
 at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
 at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
 at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
 at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.lone.itemsadder.api.CustomStack
 at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
 ... 26 more

**Minecraft Version:**
- 1.20.1

**Server Version:**
 - paper git-196 (MC: 1.20.1)

**Plugin Version**
- NoMoreCooked-0.0.8c-RELEASE

**Comment by The-Zandrax** [comment]
Hello, 

- have you activated the itemsadder option in the configuration? 
- If so, do you have Itemsadder installed on your server? 
- And if so, what version of itemsadder are you using?

**Comment by ToMrZen** [comment]
No, I have not activated the ItemAdder. I didn't touch the configuration.

**Comment by The-Zandrax** [comment]
After testing, I've indeed made a logical error in the code. I'll fix it today.

**Comment by The-Zandrax** [comment]
**Fixed in the latest version: 0.0.8d**

I've temporarily changed the code so that the error no longer occurs, I'll have to change all this again later but it solves the problem effectively at the moment.
